require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Account::GciReviewsApiColorSchemesController do

  # This should return the minimal set of attributes required to create a valid
  # Account::GciReviewsApiColorScheme. As you add validations to Account::GciReviewsApiColorScheme, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Account::GciReviewsApiColorSchemesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all account_gci_reviews_api_color_schemes as @account_gci_reviews_api_color_schemes" do
      gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:account_gci_reviews_api_color_schemes).should eq([gci_reviews_api_color_scheme])
    end
  end

  describe "GET show" do
    it "assigns the requested account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
      gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
      get :show, {:id => gci_reviews_api_color_scheme.to_param}, valid_session
      assigns(:account_gci_reviews_api_color_scheme).should eq(gci_reviews_api_color_scheme)
    end
  end

  describe "GET new" do
    it "assigns a new account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
      get :new, {}, valid_session
      assigns(:account_gci_reviews_api_color_scheme).should be_a_new(Account::GciReviewsApiColorScheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
      gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
      get :edit, {:id => gci_reviews_api_color_scheme.to_param}, valid_session
      assigns(:account_gci_reviews_api_color_scheme).should eq(gci_reviews_api_color_scheme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Account::GciReviewsApiColorScheme" do
        expect {
          post :create, {:account_gci_reviews_api_color_scheme => valid_attributes}, valid_session
        }.to change(Account::GciReviewsApiColorScheme, :count).by(1)
      end

      it "assigns a newly created account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
        post :create, {:account_gci_reviews_api_color_scheme => valid_attributes}, valid_session
        assigns(:account_gci_reviews_api_color_scheme).should be_a(Account::GciReviewsApiColorScheme)
        assigns(:account_gci_reviews_api_color_scheme).should be_persisted
      end

      it "redirects to the created account_gci_reviews_api_color_scheme" do
        post :create, {:account_gci_reviews_api_color_scheme => valid_attributes}, valid_session
        response.should redirect_to(Account::GciReviewsApiColorScheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
        # Trigger the behavior that occurs when invalid params are submitted
        Account::GciReviewsApiColorScheme.any_instance.stub(:save).and_return(false)
        post :create, {:account_gci_reviews_api_color_scheme => {  }}, valid_session
        assigns(:account_gci_reviews_api_color_scheme).should be_a_new(Account::GciReviewsApiColorScheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Account::GciReviewsApiColorScheme.any_instance.stub(:save).and_return(false)
        post :create, {:account_gci_reviews_api_color_scheme => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested account_gci_reviews_api_color_scheme" do
        gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
        # Assuming there are no other account_gci_reviews_api_color_schemes in the database, this
        # specifies that the Account::GciReviewsApiColorScheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Account::GciReviewsApiColorScheme.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => gci_reviews_api_color_scheme.to_param, :account_gci_reviews_api_color_scheme => { "these" => "params" }}, valid_session
      end

      it "assigns the requested account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
        gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
        put :update, {:id => gci_reviews_api_color_scheme.to_param, :account_gci_reviews_api_color_scheme => valid_attributes}, valid_session
        assigns(:account_gci_reviews_api_color_scheme).should eq(gci_reviews_api_color_scheme)
      end

      it "redirects to the account_gci_reviews_api_color_scheme" do
        gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
        put :update, {:id => gci_reviews_api_color_scheme.to_param, :account_gci_reviews_api_color_scheme => valid_attributes}, valid_session
        response.should redirect_to(gci_reviews_api_color_scheme)
      end
    end

    describe "with invalid params" do
      it "assigns the account_gci_reviews_api_color_scheme as @account_gci_reviews_api_color_scheme" do
        gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Account::GciReviewsApiColorScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => gci_reviews_api_color_scheme.to_param, :account_gci_reviews_api_color_scheme => {  }}, valid_session
        assigns(:account_gci_reviews_api_color_scheme).should eq(gci_reviews_api_color_scheme)
      end

      it "re-renders the 'edit' template" do
        gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Account::GciReviewsApiColorScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => gci_reviews_api_color_scheme.to_param, :account_gci_reviews_api_color_scheme => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested account_gci_reviews_api_color_scheme" do
      gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
      expect {
        delete :destroy, {:id => gci_reviews_api_color_scheme.to_param}, valid_session
      }.to change(Account::GciReviewsApiColorScheme, :count).by(-1)
    end

    it "redirects to the account_gci_reviews_api_color_schemes list" do
      gci_reviews_api_color_scheme = Account::GciReviewsApiColorScheme.create! valid_attributes
      delete :destroy, {:id => gci_reviews_api_color_scheme.to_param}, valid_session
      response.should redirect_to(account_gci_reviews_api_color_schemes_url)
    end
  end

end
